import type { Metadata } from "next";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import Navbar from "@/components/Navbar";
// import Footer from "@/components/Footer";


export const metadata: Metadata = {
  title: "Vision UI Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="flex"
        >
        <Sidebar/>
        <Navbar/>
        {children}
        {/* <Footer/> */}
      </body>
    </html>
  );
}
